name: Build Hidden Module

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: "Package name of the game (e.g. com.fun.lastwar.vn.gp):"
        required: true
        type: string

jobs:
  build:
    name: Build Hidden Module
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Java 11 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: gradle

      - name: Patch identifiers (anti-detect)
        run: |
          chmod +x ./gradlew
          echo "Using package name: ${{ github.event.inputs.package_name }}"

          # Ghi package name vào file game.h
          sed -i "s/com.game.packagename/${{ github.event.inputs.package_name }}/g" module/src/main/cpp/game.h

          # Cập nhật mô tả module (ẩn tên thật)
          sed -i 's/moduleDescription = "/moduleDescription = "('${{ github.event.inputs.package_name}}') /g' module.gradle

          # Ẩn thông tin module.prop — tránh từ khóa bị phát hiện
          sed -i 's/${id}/com.system.runtimehelper/g' module/module.prop
          sed -i 's/${name}/System Runtime Helper/g' module/module.prop
          sed -i 's/${version}/1.0.0/g' module/module.prop
          sed -i 's/${versionCode}/1/g' module/module.prop
          sed -i 's/${author}/system/g' module/module.prop
          sed -i 's#${description}#Enhances app runtime compatibility#g' module/module.prop

      - name: Build release module
        run: ./gradlew :module:assembleRelease --stacktrace

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: system-runtimehelper-${{ github.event.inputs.package_name }}
          path: out/magisk_module_release/
          if-no-files-found: error
